runtime: nodejs
vm: true
env_variables:
  PAGE_ACCESS_TOKEN: 'EAAEtioEMowoBAGW8hKibwNLto7KgOQsgbHIwkmLpuKLIWnWpaXJnprO4R8Py8jB5Lc9V1jZANWVCvZAvB2V42cTbsjmtb95PBIl0YF2ooC4a4LWvvqXFFb31J1sgHW7bZBRE4bVVwGK76ZCg1ghVF9dRZBofObsDqCQraIGnxEAZDZD'